# Generated by Django 3.0.6 on 2020-06-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('vendor_name', models.CharField(choices=[('Kinda Home', 'Kinda Home'), ('Inovia', 'Inovia'), ('Casacon', 'Casacon'), ('NCR Angola', 'NCR Angola'), ('Seaside', 'Seaside'), ('Soba-store', 'Soba-store'), ('Megáfrica', 'Megáfrica'), ('Maxi', 'Maxi'), ('Meu Merkado', 'Meu Merkado')], default=1, max_length=100, verbose_name='Vendor Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Product Price')),
                ('disc_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Product Dicount Price')),
                ('disc_off', models.IntegerField(blank=True, verbose_name='Price Off')),
                ('description', models.TextField(blank=True, verbose_name='Product Description')),
                ('link_vendor', models.URLField(max_length=2048, verbose_name='Vendor Link')),
                ('link_image', models.URLField(max_length=2048, verbose_name='Product Image Link')),
                ('category', models.CharField(choices=[('Eletrônicos', 'Eletrônicos'), ('Fashion & Acessórios', 'Fashion & Acessórios'), ('Jogos', 'Jogos'), ('Casa & Lar', 'Casa & Lar'), ('Família & Crianças', 'Família & Crianças'), ('Jardim', 'Jardim'), ('Saúde & Beleza', 'Saúde & Beleza'), ('Desporto', 'Desporto'), ('Escritório', 'Escritório')], default=1, max_length=200, verbose_name='Product category')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Time of Creation')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Ads',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Time of Creation')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_user'),
        ),
        migrations.AddConstraint(
            model_name='ads',
            constraint=models.UniqueConstraint(fields=('name', 'link_vendor'), name='unique_ads'),
        ),
    ]
