# Generated by Django 3.0.6 on 2020-06-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200618_1355'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ads',
            constraint=models.UniqueConstraint(fields=('link_vendor',), name='unique_ads'),
        ),
    ]
