# Generated by Django 3.0.6 on 2020-06-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200618_1355'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ads',
            name='unique_ads',
        ),
        migrations.AlterUniqueTogether(
            name='ads',
            unique_together={('name', 'link_vendor')},
        ),
    ]
